DROP SCHEMA IF EXISTS "public" CASCADE;
DROP SCHEMA IF EXISTS "tables" CASCADE;
DROP SCHEMA IF EXISTS "relations" CASCADE;

CREATE SCHEMA "public";
CREATE SCHEMA "tables";
CREATE SCHEMA "relations";

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "plpython3u";